Adding Bug Report template
marzvfx/.github pull request #4
Opened 2021-09-29 16:31 UTC by NevsTD-MARZ

2021-09-29 17:58 UTC, coshio-marz requested changes
I like it. 
The only thing id add is a section of how many times the bug was able to be reproduced. This helps determine if the issue is intermittent or not and could be related to network issues or some other hidden variable that cannot be accounted for.

2021-09-29 20:05 UTC, NevsTD-MARZ commented
> I like it. The only thing id add is a section of how many times the bug was able to be reproduced. This helps determine if the issue is intermittent or not and could be related to network issues or some other hidden variable that cannot be accounted for.

Good idea.
Please see the update; I've added it as a sub-section of "Additional Context"

Based on something @kmiddlemiss said in the OKR Tech meeting we just had, I thought adding a "Stakeholder" section would also be really useful.
The update also includes that.

2021-09-29 20:06 UTC, rabolmolouk approved these changes

2021-10-01 18:33 UTC, kmiddlemiss approved these changes

2021-10-01 18:33 UTC, merged